ROLE_USER = 0
ROLE_ADMIN = 1

ROLE_USER_TEXT = 'user'
ROLE_ADMIN_TEXT = 'admin'

USER_NON_BLOCK = 0
USER_BLOCK = 1

RESPONSE_SUCCESS = 'success'
RESPONSE_ERROR = 'error'

USER_BLOCK_RESPONSE = 'user block'